services:
  bdtracker:
    build: .
    container_name: bdtracker
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - BD_ROOT_DIR=/app/data/bdtracker.db
      - BD_RAW_HOSTS=your_allowed_hosts       # e.g. "your_domain.com,192.168.1.1,localhost,etc"
      - BD_RAW_ORIGINS=your_allowed_origins   # e.g. "https://your_domain.com,http://localhost,etc"
      - BD_ADMIN_MASTER_KEY=your_admin_token  # python -c "import secrets; print(secrets.token_urlsafe(32))"
